# Dockerfile.student
FROM golang:1.25.1-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
ENV GOPROXY=https://goproxy.cn,direct
ENV GOSUMDB=off
RUN go mod download
COPY . .
RUN go build -o student-server cmd/student/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/student-server .
COPY config/config.yaml ./config/
EXPOSE 8081
CMD ["./student-server"]
