FROM golang:1.25.1-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
ENV GOPROXY=https://goproxy.cn,direct
ENV GOSUMDB=off
RUN go mod download
COPY . .
RUN go build -o backend-server ./api/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/backend-server .
COPY config/config.docker.yaml ./config/config.yaml
EXPOSE 18080
CMD ["./backend-server"]
